pipeline {
  agent { label 'php-agent' }

  stages {
    stage('Install Dependencies') {
      steps {
        dir('Lab 4/recipe-book') {
          echo 'Подготовка проекта...'
          sh '''
            set -e
            php -v
            curl -sS https://getcomposer.org/installer -o composer-setup.php
            php composer-setup.php --install-dir=/usr/local/bin --filename=composer
            composer install --no-interaction --prefer-dist
          '''
        }
      }
    }

    stage('Test') {
      steps {
        dir('Lab 4/recipe-book') {
          echo 'Запуск тестов...'
          sh '''
            set -e
            vendor/bin/phpunit --configuration phpunit.xml
          '''
        }
      }
    }
  }

  post {
    always { echo 'Конвейер завершен.' }
    success { echo 'Все этапы прошли успешно!' }
    failure { echo 'Обнаружены ошибки в конвейере.' }
  }
}